# Generated by Django 2.1.7 on 2019-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190405_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grad_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
