# Generated by Django 2.1.7 on 2019-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190407_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnections',
            name='conn_status',
            field=models.IntegerField(choices=[(1, 'Connected'), (2, 'Pending')], default=0),
        ),
    ]
